# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: daven55663.SentriPet
PackageVersion: 2.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: SentriPet.exe
  PortableCommandAlias: sentripet
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/daven55663/SentriPet-AI/releases/download/v2.2.1/SentriPet-2.2.1-win-x64.zip
  InstallerSha256: 30EC5CBF4979B091C60DD7B3647E02F14510C5D85868C930889AF83F33D1A52D
ManifestType: installer
ManifestVersion: 1.12.0
